/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface QuillComponent {
    'content': string;
  }
  interface QuillComponentAttributes extends StencilHTMLAttributes {
    'content'?: string;
    'onOnContentChanged'?: (event: CustomEvent<{
      editor: any
      delta: any
      oldDelta: any
      source: string
    }>) => void;
    'onOnInitialised'?: (event: CustomEvent<any>) => void;
    'onOnSelectionChanged'?: (event: CustomEvent<{
      editor: any
      range: any
      oldRange: any
      source: string
    }>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'QuillComponent': Components.QuillComponent;
  }

  interface StencilIntrinsicElements {
    'quill-component': Components.QuillComponentAttributes;
  }


  interface HTMLQuillComponentElement extends Components.QuillComponent, HTMLStencilElement {}
  var HTMLQuillComponentElement: {
    prototype: HTMLQuillComponentElement;
    new (): HTMLQuillComponentElement;
  };

  interface HTMLElementTagNameMap {
    'quill-component': HTMLQuillComponentElement
  }

  interface ElementTagNameMap {
    'quill-component': HTMLQuillComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
